name: First Workflow
on: workflow_dispatch #możemy manualnie uruchomić workflow

jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print 1
        run: |
          echo "O nie..."
          echo "...skasowalem Windowsa."        
